
[package]
name = "veseliy_pjt_usb"
build = "src/resources/build.rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
rusb = "0.9.1"
byteorder = {version = "1", features = ["i128"]}
packed_struct = "0.10.0"
iced = { version = "0.7", features = ["debug", "svg"] }
iced_native = "0.9.0"
iced_lazy = "0.5.0"
image = "0.24.5"

[dependencies.iced_aw] 
git = "https://github.com/iced-rs/iced_aw"
rev="b66f93bcb27d4ea94c7e6d68ac4cf78535ebbabc" #latest commit as of 18.02.2023 v0.3.0
default-features = false 
features = [ "menu", "quad", "icon_text", "tabs", "grid"]

[build-dependencies]
winresource = "0.1.14"

[package.metadata.winresource]
ProductName = "open_mc56f_usbdm"
LegalCopyright = "GPL v2 © 2022"

