
[package]
name = "veseliy_pjt_usb"
build = "src/resources/build.rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.9.1"
byteorder = {version = "1", features = ["i128"]}
packed_struct = "0.10.0"
iced = { version = "0.7", features = ["debug"] }
iced_native = "0.8.0"
iced_aw = {version = "0.3", default-features = false, features = ["tabs", "grid"] }
iced_lazy = "0.4.0"
image = "0.24.5"

[build-dependencies]
winresource = "0.1.14"

[package.metadata.winresource]
ProductName = "open_mc56f_usbdm"
LegalCopyright = "GPL v2 © 2022"